import 'bootstrap/dist/css/bootstrap.min.css';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SessionAuthProvider from '@/context/SessionAuthProvider';
import Header from '@/components/Header';
import './globals.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className='container-fluid'>
          <div className="row min-vh-100"> 
            <div className="col"> 
              <SessionAuthProvider>{children}</SessionAuthProvider>
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}